{
 "title": "Davide HPA Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU Consumption by Service (Total mcore)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service) (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"compose.*\"}[2m]))\n",
     "legendFormat": "compose-post"
    },
    {
     "expr": "sum by (service) (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"nginx.*\"}[2m]))\n",
     "legendFormat": "nginx-thrift"
    },
    {
     "expr": "sum by (service) (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"text.*\"}[2m]))\n",
     "legendFormat": "text-service"
    },
    {
     "expr": "sum by (service) (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"user-mention.*\"}[2m]))\n",
     "legendFormat": "user-mention-service"
    }
   ]
  },
  {
   "title": "CPU Utilization per Service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"compose.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"compose.*\"}) * 100\n",
     "legendFormat": "compose-post-service"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"nginx.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"nginx.*\"}) * 100\n",
     "legendFormat": "nginx-thrift"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"text.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"text.*\"}) * 100\n",
     "legendFormat": "test-service"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"user-mention.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"user-mention.*\"}) * 100\n",
     "legendFormat": "user-mention-service"
    }
   ]
  },
  {
   "title": "Replicas per Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"compose.*\"})\n",
     "legendFormat": "compose-post"
    },
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"nginx.*\"})\n",
     "legendFormat": "nginx-thrift"
    },
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"text.*\"})\n",
     "legendFormat": "test-service"
    },
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"user-mention.*\"})\n",
     "legendFormat": "user-mention-service"
    }
   ]
  }
 ]
}