{
 "title": "HPA Shared Info",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU Consumption by Service (Total mcore)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service) (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"compose.*\"}[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (service) (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"nginx.*\"}[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (service) (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"text.*\"}[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (service) (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"user-mention.*\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utillization per service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"compose.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"compose.*\", app_kubernetes_io_instance=\"prometheus\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"nginx.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"nginx.*\", app_kubernetes_io_instance=\"prometheus\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"text-service.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"text-service.*\", app_kubernetes_io_instance=\"prometheus\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"user-mention.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"user-mention.*\", app_kubernetes_io_instance=\"prometheus\"}) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas per service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"compose.*\", app_kubernetes_io_instance=\"prometheus\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"nginx.*\", app_kubernetes_io_instance=\"prometheus\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"text-service.*\", app_kubernetes_io_instance=\"prometheus\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"user-mention.*\", app_kubernetes_io_instance=\"prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}